name: dw
version: '1.0.0'
config-version: 2

profile: dw

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
docs-paths: ["docs"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  batch_date: ""
  batch_start_date: ""
  batch_end_date: ""

models:
  dw:
    +materialized: view
    01-stg:
      +docs:
        node_color: "#5DADE2"
    02-core:
      transactional-fact:
        +docs:
          node_color: "#27AE60"
      periodic-snapshot-fact:
        +docs:
          node_color: "#E67E22"
      scd1:
        +docs:
          node_color: "#8E44AD"
    03-marts:
      accumulating-snapshot-fact:
        +docs:
          node_color: "#D35400"
      periodic-snapshot-fact:
        +docs:
          node_color: "#BA4A00"
