name: dw
version: '1.0.0'
config-version: 2

profile: dw

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
docs-paths: ["docs"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  batch_date: ""
  batch_start_date: ""
  batch_end_date: ""

models:
  dw:
    +materialized: view
