sources:

  - name: gharchive
    description: "GitHub Archive Dataset"
    dataset: raw__gharchive
    config:
      meta:
        owner: joshua
    
    tables:
      - name: events
        identifier: ext__events
        description: "GitHub Archive Events Table"
        config:
          tags: ["source", "gharchive", "fact"]
          loaded_at_field: "safe_cast(ingested_at as timestamp)"
          freshness:
            warn_after: { count: 2, period: hour }
            error_after: { count: 6, period: hour }
            filter: "dt >= current_date - 2"
