version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
    assignees:
      - joshua-data

  - package-ecosystem: pip
    directory: /dbt
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(dbt)
    assignees:
      - joshua-data
